### ISSUE TITLE
Where to use this package

### ISSUE THREAD

**Issue by HenrikGr** [ITECOMMPAY/paymentpage-sdk-js#13]
Hi,

I have read your documentation over and over again and I can not figure out where to use this package. 

Should this package be used in the backend, lets say I have a node.js app that my frontend sends http request to, including parameters to create a Payment instance on the backend, and also generate a payment form invokation request via the getUrl() method, can I send that url back to my client that opens the payment form?

Or, should this package be used on my client, together with your widget and javascript files and css files?

**Comment by zhukovra** [comment]
Hi, @HenrikGr.

Your first assumption is right. With that package, you can generate URL to payment page for your clients. In README example you can see `secret` argument - it's a real secret key that you get from our support team. That secret shouldn't be exposed to public area.

**Comment by HenrikGr** [comment]
Thank you for your answer. Just a follow up question. 

When my mobile app receives the url from the backend, do my mobile app have to follow any requirements such as design template etc specified in this link?
https://developers.ecommpay.com/en/en_PP__design_requirements.html or is this only if I'm choose to use the widget solution on the frontend?

**Comment by zhukovra** [comment]
No. This is design requirements for custom Payment page design. You can ask all questions about integration details here - support@ecommpay.com

We also developing Android and iOS SDK's for native integration.

**Comment by HenrikGr** [comment]
I have asked support and they say this package is used with the widget solution.
I do not think so and that's why I ask here instead.

Just to clarify, what do you mean with custom payment design?
Does it exist any samples?

**Comment by zhukovra** [comment]
I don't know may I show any customized screens due to our legal policy. I'll try to find out that.
You can talk about custom design of Payment Page (html widget) with your manager from Ecommpay.
